spring:
  application:
    name: test
    domain-properties:
      sport-events-source:
        url: ${EVENT_SOURCE_SERVICE_URL}
      kafka:
        score-updates-topic: score-updates
      poll-interval: 10s
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    client-id: ${spring.application.name}

    producer:
      acks: all
      retries: 2147483647
      max-in-flight-requests-per-connection: 5
      linger-ms: 5
      compression-type: snappy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        auto.register.schemas: true
        specific.avro.reader: true

    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL}
